### ISSUE TITLE
Not able to create build on Windows platform (Tried using different methods)

### ISSUE THREAD

**Issue by hassanmehmud** [a-rmz/JEasyCrypto#22]
## Description
I tried exporting jar files using bash code on windows, i even used many work around but it provides same error with json methods and some language exceptions almost 22 errors in row

## Steps to Reproduce the Problem
1: Try to compile the whole build, you will receive errors with json and client api (Ref to issue_windows_1)
2: If you build and start client separately as instructed, language exception error will come out may its because wrong path directory to main class - not sure (Ref to issue_windows_2)

## Expected Behavior
It should create a build and run

## Actual Behavior
Doesn't work, shows error

  - Platform: Windows 10
  - Platform: MAC OS

## Additional info
Well there is a strange thing , it works correctly with linux environment, i dont know if windows is lacking bash support. Looks like we need to work on Linux, if anybody is able to resolve it please comment, i myself looking into it.
![issue_windows_1](https://user-images.githubusercontent.com/32633075/31380926-8cf9c4a8-adbb-11e7-8b30-56790aa7513a.PNG)
![issue_windows_2](https://user-images.githubusercontent.com/32633075/31380927-8d675824-adbb-11e7-968c-c0e84c7016aa.PNG)

**Comment by risju62** [comment]
I tried this also yeaterday evening, seems that java can't find simple-json.jar. Perhaps classpath should be represented differently in windows?

**Comment by anttijuu** [comment]
This like all issues, can be fixed by contributors. Anyone catching this? I can say that yes, the build.sh are for *nix (linux, mac) and require some editing for windows. Not complex, little googling or a peek to stackoverflow.com helps. So anyone can create a build file for Windows, e.g. a .bat file. Just a side note, I am not a contributor here ;)

**Comment by hassanmehmud** [comment]
Yes i have bat file workaround in my mind, i will do that in evening. but strange thing is it is happening with Mac as well, my group has mac machine it was almost on it as well.

**Comment by anttijuu** [comment]
You need to build the library _first_ and it must be exported to a .jar file in the correct directory (build.sh does this). The json lib must also reside there. Then you can build the console, client and server. Maybe this is the problem.
