### ISSUE TITLE
Getting rid of hard-coded integers in CryptoClient

### ISSUE THREAD

**Issue by sfatali** [a-rmz/JEasyCrypto#39]
**Description**

In CryptoClient.java class there is a method: selectMenuItem(). It uses hard-coded integers (like: 1, 2, 3, 4) when printing possible actions for user to choose (encrypt, decrypt e.t.c.). 

[https://github.com/a-rmz/JEasyCrypto/blob/develop/JEasyCryptoClient/src/CryptoClient.java](url)

My suggestion for improvement would be to use constants instead of the integers, since they are already defined in the class (CAPABILITY_MENU e.t.c). 

Because with time, someone may alter the constants' values, but in the printing they may stay the same (if that person forgets to change them there). Or even if does not forget - why repeating the same work twice, when constants are already there and can be used nicely.

This is just for possible enhancement.

**Comment by a-rmz** [comment]
Sounds good, thanks for the suggestion.

**Comment by sfatali** [comment]
I started working on it too. There are also some other ideas on how to make Menu constants and related "handle" methods more flexible for future extensions. Will try to submit the code during weekend.

**Comment by a-rmz** [comment]
@sfatali I will close this issue, since a GUI has already been implemented ( #49 ), "upgrading" the CLI UI is not a priority anymore.
