### ISSUE TITLE
Adding "bin" folder to gitignore and deleting it from remote repository completely

### ISSUE THREAD

**Issue by sfatali** [a-rmz/JEasyCrypto#52]
**Description**

I think it can be a good idea to add "bin" folder to gitignore and delete the folder from remote repository. No use in transferring the .class files from place to place, they only create unnecessary work: stashing, resolving occasional conflicts e.t.c.

**Comment by a-rmz** [comment]
This has been already fixed on the [latest](https://github.com/a-rmz/JEasyCrypto/commit/0ba6bbfc9caa81652aafbf4bcb3c3e639021f647) commit of the `.gitignore`. You can also see that the `bin/` directory is no longer in the repo.

![image](https://user-images.githubusercontent.com/15201480/31809048-97c6b916-b57e-11e7-9971-6d9f9c5f2f74.png)

If you don't see this changes, please [update your fork](https://github.com/a-rmz/JEasyCrypto/blob/develop/CONTRIBUTING.md#step-4-rebase) so you have the latest version.
