### ISSUE TITLE
CryptoClient NullPointerException

### ISSUE THREAD

**Issue by ajrussell999** [a-rmz/JEasyCrypto#54]
## Description
CryptoClient crashes with error message, NullPointerException in thread main.

## Steps to Reproduce the Problem

  1. Run CryptoClient.java in eclipse IDE.
  2. Observe NullPointerException in eclipse console. 

## Expected Behavior
Menu prompt for encryption service
"Welcome to CryptoClient!"

## Actual Behavior
Exception in thread "main" java.lang.NullPointerException
	at CryptoClient.run(CryptoClient.java:79)
	at CryptoClient.main(CryptoClient.java:101)

## Reproduces how often: [What percentage of the time does it reproduce?]
100%.

## Specifications

  - Version: Branch. develop 4e9d014 Merge pull request #46 from a-rmz/revert-44-Keys
  - Platform:JRE System Library [JavaSE8 [1.8.0_74)]

**Comment by anttijuu** [comment]
You cannot debug/run apps which use the java.io.Console class for input/output. See [stackoverflow](https://stackoverflow.com/questions/104254/java-io-console-support-in-eclipse-ide) discussion. The discussion also explains how to set up remote debugging with Eclipse, for apps using Console, if that is what you were about to do.

**Comment by ajrussell999** [comment]
Issue not with the JCryptoServer code but how eclipse IDE runs code.
The problem is that System.console() returns null when an application is run "through" Eclipse. Eclipse runs the program on a background process, rather than a top-level process with the console window we're familiar with.
More details at, https://stackoverflow.com/questions/104254/java-io-console-support-in-eclipse-ide
