### ISSUE TITLE
[Client/Server] Exotic character break the encryption

### ISSUE THREAD

**Issue by a-rmz** [a-rmz/JEasyCrypto#8]
## Description
If using äö (or anything else exotic) with reverse/matrix methods, it fails on Client/Server but not on console.

## Steps to Reproduce the Problem
  1. Send a message through the client encrypted with reverse/matrix.
  2. :boom:

## Expected Behavior
Get the proper encrypted/decrypted message.

## Reproduces how often: [What percentage of the time does it reproduce?]
Every time.

## Additional info
Related to #7.

**Comment by risju62** [comment]
This issue does not manifest itself, if both server and client are running on same windows mahchine.

**Comment by anttijuu** [comment]
See also issue #7 since these are related, as a-rmz referenced above.

**Comment by Lrantala** [comment]
Issue #7 patch fixed this problem, so the issue can be closed.

**Comment by a-rmz** [comment]
Fixed in #7.
